### ISSUE TITLE
Migration crashes with "TypeError: Incorrect padding" 

### ISSUE THREAD

**Issue by Brownrp92** [ergon/migratemost#8] opened 2019-07-31 18:16 UTC
**Error Below is only when using --migrate-all**

[srcadmin@LX-VM-MATMOST migratemost]$ sudo python migratemost.py -t teamtest1 -o dataout -i datain -v --concat-output --migrate-all
2019-07-31 14:06:55,090 - INFO - Starting migration
2019-07-31 14:06:55,090 - INFO - Team migration started
2019-07-31 14:06:55,091 - INFO - Team migration finished
2019-07-31 14:06:55,091 - INFO - User migration started
Traceback (most recent call last):
  File "migratemost.py", line 1271, in <module>
    main()
  File "migratemost.py", line 1108, in main
    mm_users = migrate_users()
  File "migratemost.py", line 585, in migrate_users
    'mm_user_%s_avatar' % mm_user.get_hc_id())
  File "migratemost.py", line 563, in store_base64_image
    img = Image.open(BytesIO(base64.b64decode(data)))
  File "/usr/lib64/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

 **I also get the error below during --migrate-channel-posts**

[srcadmin@LX-VM-MATMOST migratemost]$ sudo python migratemost.py -t teamtest1 -o dataout -i datain -v --migrate-channel-posts
2019-07-31 14:10:49,766 - INFO - Starting migration
2019-07-31 14:10:49,767 - INFO - Team migration started
2019-07-31 14:10:49,767 - INFO - Team migration finished
2019-07-31 14:10:49,767 - INFO - User migration started
2019-07-31 14:10:49,799 - INFO -        Found 1102 deleted users. Writing file users_to_deactivate.txt to be used with Mattermost CLI to deactivate them.
2019-07-31 14:10:49,802 - INFO - User migration finished
2019-07-31 14:10:49,802 - INFO - Channel migration started
2019-07-31 14:10:49,838 - INFO -        Found 2 archived channels. Writing file channels_to_archive.txt to be used with Mattermost CLI to archive them.
2019-07-31 14:10:49,838 - DEBUG -       323 channels migrated
2019-07-31 14:10:49,861 - INFO -        Migrating posts of channel (name: default) 0/323
2019-07-31 14:10:49,866 - DEBUG -               0 posts migrated
2019-07-31 14:10:49,866 - INFO -        Migrating posts of channel (name: test_room1) 1/323
2019-07-31 14:10:49,872 - DEBUG -               0 posts migrated
2019-07-31 14:10:49,872 - INFO -        Migrating posts of channel (name: pnts) 2/323
Traceback (most recent call last):
  File "migratemost.py", line 1271, in <module>
    main()
  File "migratemost.py", line 1142, in main
    mm_posts = migrate_channel_posts(mm_username_by_hc_id, channel)
  File "migratemost.py", line 728, in migrate_channel_posts
    if hc_message['attachment'] is not None:
KeyError: 'attachment'

[srcadmin@LX-VM-MATMOST migratemost]$ python --version
Python 2.7.5

**Any assistance is greatly appreciated, thank you.**

**Comment by 7-plus-t** [comment] 2019-08-02 17:57
What HipChat edition and version did you export from?

**Comment by Brownrp92** [comment] 2019-08-05 12:18
Atlassian HipChat 2.4.1 (2018.07.19.134050)

**Comment by 7-plus-t** [comment] 2019-08-05 13:58
I will add some additional logging for easier debugging. Stay tuned.

**Comment by 7-plus-t** [comment] 2019-08-12 09:04
@Brownrp92 I've just pushed two commits which should help with your issue. Please try again and check the log for `Failed to decode base 64 data` messages.

**Comment by Brownrp92** [comment] 2019-08-12 15:41
**Here is the new error, I tried to locate the files and they do not exist. There is only files/img/emoticons   no files/photos**

[srcadmin@LX-VM-MATMOST migratemost]$ sudo python migratemost.py -t team-test -o dataout -i datain -v --concat-output --migrate-all
2019-08-12 11:39:58,732 - INFO - Starting migration
2019-08-12 11:39:58,732 - INFO - Team migration started
2019-08-12 11:39:58,732 - INFO - Team migration finished
2019-08-12 11:39:58,732 - INFO - User migration started
2019-08-12 11:39:58,751 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/14/K4DcSjZwLqatQD7.jpg
2019-08-12 11:39:58,752 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/24/HmRkcGBC3owszIa.jpg
2019-08-12 11:39:58,752 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/26/QP1zcSwf4xPp3lE.jpg
2019-08-12 11:39:58,752 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/38/huokEJnxR8MDUpy.png
2019-08-12 11:39:58,752 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/39/Ik737zPpnz0zEhp.jpg
2019-08-12 11:39:58,752 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/46/4LwNdQ9MZI9xUgp.gif
2019-08-12 11:39:58,752 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/51/pqr0nI6F9qsd4sD.jpg
2019-08-12 11:39:58,753 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/120/UUH7uyjJPS4qm03.png
2019-08-12 11:39:58,753 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/125/G39tuIYXsqrpZye.jpg
2019-08-12 11:39:58,753 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/151/T35AH8tVhat54QU.jpg
2019-08-12 11:39:58,754 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/167/7HrgrPaEhM30in2.jpg
2019-08-12 11:39:58,754 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/205/xHGlhAzOPzWjwzg.png
2019-08-12 11:39:58,754 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/212/aT16flcRbZDE42O.jpg
2019-08-12 11:39:58,754 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/220/3LKoDtyh7CvvsHi.jpg
2019-08-12 11:39:58,755 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/226/gT5PTnh7knvuCyd.jpg
2019-08-12 11:39:58,755 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/236/EBgqFJ45fhfhxf9.png
2019-08-12 11:39:58,755 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/251/udlw4nGYoeZfj9L.jpg
2019-08-12 11:39:58,755 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/260/jzY3A7b2825GuXT.png
2019-08-12 11:39:58,755 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/265/sTWe1V0Gh9ujRYc.jpg
2019-08-12 11:39:58,755 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/274/nHtXI8saUyLz7mL.png
2019-08-12 11:39:58,756 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/286/OsyagWlHZwMKR6T.jpg
2019-08-12 11:39:58,756 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/298/B2rUgnt4YO8uioi.jpg
2019-08-12 11:39:58,756 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/299/FZAq5zXmEcp3rEM.jpg
2019-08-12 11:39:58,756 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/306/LS76QseM5UhfosC.jpg
2019-08-12 11:39:58,756 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/318/pnRMuYFr9GS1iE2.png
2019-08-12 11:39:58,757 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/326/BuEreCCKAV5Ge1Q.png
2019-08-12 11:39:58,757 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/399/JWZiWz8HGLEMoYs.jpg
2019-08-12 11:39:58,757 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/426/768mhHrAch35Wc8.jpg
2019-08-12 11:39:58,758 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/437/aiDpPJ5EJIs836Z.png
2019-08-12 11:39:58,758 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/438/X4DCw4VEqPdkcdC.jpg
2019-08-12 11:39:58,758 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/447/G4pLtCa10En2UGV.jpg
2019-08-12 11:39:58,758 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/450/R0tCMeZeNE1GeJ1.jpg
2019-08-12 11:39:58,758 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/453/13U8jEfPXH9dAZA.jpg
2019-08-12 11:39:58,758 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/454/evsFghsBCPqPctT.png
2019-08-12 11:39:58,759 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/480/R3xJg4LCfkB8ptq.jpg
2019-08-12 11:39:58,759 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/513/8Sv7f1UjWmlvsvZ.jpg
2019-08-12 11:39:58,759 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/514/MreonbUn5DISBwk.jpg
2019-08-12 11:39:58,759 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/521/ufLWkjJT5kmoeBE.gif
2019-08-12 11:39:58,759 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/535/f9wvviTBtcYP7Yl.jpg
2019-08-12 11:39:58,760 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/549/stzVlxLCIGz5LHs.png
2019-08-12 11:39:58,761 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/577/tdgMU2CVPj5XZs0.png
2019-08-12 11:39:58,762 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/618/Fp1AYPIWW1BpJSi.jpg
2019-08-12 11:39:58,762 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/628/zKasrWtlVdxkJHv.jpg
2019-08-12 11:39:58,762 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/629/3hxp748genhdqMD.png
2019-08-12 11:39:58,762 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/641/GNcn2UOYAxZbWLA.jpg
2019-08-12 11:39:58,762 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/680/OfDwgeKh69UIDER.png
2019-08-12 11:39:58,763 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/712/nsK8zKI4kt8iK0c.jpg
2019-08-12 11:39:58,763 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/723/7CWe13r2JJ2UBTb.png
2019-08-12 11:39:58,763 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/724/f8hvpwydY1Gta90.png
2019-08-12 11:39:58,763 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/727/JQHjKQvKTc288ms.jpg
2019-08-12 11:39:58,763 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/736/iKAAiwsU86z8Gsb.jpg
2019-08-12 11:39:58,764 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/756/iknOMqEhHte29dA.png
2019-08-12 11:39:58,764 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/782/jf1zfzAwZJIeSgd.png
2019-08-12 11:39:58,764 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/784/Vck10Z37cjnDx0c.jpg
2019-08-12 11:39:58,764 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/801/Y4zlC1U16YkrC3v.jpg
2019-08-12 11:39:58,764 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/803/ktY0JUNBbZRUOid.png
2019-08-12 11:39:58,765 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/810/6y9ZpNhwZyrhO3p.png
2019-08-12 11:39:58,765 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/828/amSYU3gB6FowJkR.jpg
2019-08-12 11:39:58,765 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/835/aymmrGAbPsvpgla.jpg
2019-08-12 11:39:58,765 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/841/yzWOqLkRxUgvDpZ.jpg
2019-08-12 11:39:58,765 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/846/THcdo9M1SIPLH1y.jpg
2019-08-12 11:39:58,766 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/856/YJit4iocCuJJ62j.jpg
2019-08-12 11:39:58,766 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/857/5Vp9Ish7kcrU5CG.jpg
2019-08-12 11:39:58,766 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/878/TIYLVwqCWrjrgAr.png
2019-08-12 11:39:58,766 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/886/sdowYTMeEh9ZNxT.png
2019-08-12 11:39:58,766 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/911/S4GbCdFi5lYFwp5.png
2019-08-12 11:39:58,767 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/938/e0JTbNOSQ4aVZWH.jpg
2019-08-12 11:39:58,767 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/958/ZxiaZZx7ZF91H9p.jpg
2019-08-12 11:39:58,767 - ERROR - Failed to decode base 64 data (Incorrect padding): files/photos/992/jx3bMT0470oYsGy.jpg
Traceback (most recent call last):
  File "migratemost.py", line 1277, in <module>
    main()
  File "migratemost.py", line 1114, in main
    mm_users = migrate_users()
  File "migratemost.py", line 591, in migrate_users
    'mm_user_%s_avatar' % mm_user.get_hc_id())
  File "migratemost.py", line 569, in store_base64_image
    img = Image.open(BytesIO(decoded))
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 2822, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
IOError: cannot identify image file <_io.BytesIO object at 0x7f9bde955bf0>

**Comment by Brownrp92** [comment] 2019-08-14 18:54
Possibly an Export issue?

**Comment by Brownrp92** [comment] 2019-08-14 20:17
Any idea on what the cause of this issue may be? We are attempting to fix an upgrade issue on the Hipchat side(failed upgrade to 4.3), maybe this could be the cause of the padding issue? Thanks in advance.

**Comment by 7-plus-t** [comment] 2019-08-20 07:43
It looks like your version of Hipchat exports the avatars not as base64 data in the json but as paths to the image files. Could you check if the files are present in your export directory, f.x. does `files/photos/886/sdowYTMeEh9ZNxT.png` exist? If so, I will change the the code to accept image files directly as a fallback.

**Comment by 7-plus-t** [comment] 2019-09-17 14:43
@Brownrp92 Did you have a chance to check if the avatars are base64 encoded in the JSON or referenced by path in the Hipchat export?

**Comment by Brownrp92** [comment] 2019-09-17 15:57
I apologize for the delay, we have opted out of migrating data and have only migrated our users to Mattermost. Unfortunately I have cleaned up our export files as-well.

**Comment by 7-plus-t** [comment] 2019-09-17 16:01
Sorry to hear, I hope it was not the issues with Migratemost that caused you opt out of the data migration. Closing this issue as there is no way to reproduce it anymore.

**Closed as completed by 7-plus-t** 2019-09-17 16:01 UTC
